### PR TITLE
Improve Code Quality

### PR DESCRIPTION
**Pull request by iamcarbon**
- Makes HWStack generic to reduce casts and improve codegen
- Inlines variable declarations
- Uses pattern matching
- Adds readonly annotations

### CODE REVIEW

**Comment by iamcarbon** [comment]
This PR makes no functional or API changes. Ready for review.

**Comment by iamcarbon** [comment]
@lovettchris Ping.

**Review by lovettchris — APPROVED** [review]
Thanks, nice set of changes!

**Comment by lovettchris** [comment]
Released as [https://www.nuget.org/packages/Microsoft.Xml.SgmlReader/1.8.17](https://www.nuget.org/packages/Microsoft.Xml.SgmlReader/1.8.17).

**Pull request merged**
