### PR TITLE
Dev/2021 07 cleanup

### PR DESCRIPTION
**Pull request by daiplusplus**
This PR is intended to follow-on from https://github.com/lovettchris/SgmlReader/pull/19 - of course if any future changes are made to that before it's merged then I'll rebase this.

The impetus for this is to fix the issues caused by having different filenames for the target assembly file in a single package, which is the cause of this issue: https://github.com/lovettchris/SgmlReader/issues/11 - there is an existing PR for this ( https://github.com/lovettchris/SgmlReader/pull/12 ) but I feel that's more of a band-aid than a proper fix for redundant projects that this PR aims to solve.

- Removes the separate "Core" and "Dll" projects and combines them back into a single `.csproj`.
- Removes the (now obviated) `.nuspec` file in preference to the `.csproj`-derived `nuspec`.
- I'd like clarification on the fate of the UWP project - given that UWP projects can use .NET Standard 2.0 projects just fine is there any reason to keep it around?
- If this looks okay so far I'd like to propose the following more changes I'll add to this PR:
  - Splitting-up separate types to files - it's already difficult to manage having almost all of the types sharing the same `.cs` files. Is there a reason for this arrangement?
    - UPDATE: I got carried-away again... see commit 121483accdf46093441c6756c9f973d1a19bef87 
  - Adding .NET Core 3.1+ nullable annotations.
  - Adding async support.

### CODE REVIEW

**Comment by lovettchris** [comment]
So you are abandoning PR#12 ?  Can you close it?  if not I will go ahead and close #12.

**Comment by lovettchris** [comment]
It is too hard to review this with all the whitespace changes in it also, so I want to complete #19 so we can come back to this after that is merged.  I like the idea of merging the projects back into one, but it breaks strong naming.  I'm also not sure project generated nuspec can replace my richer SgmlReaderCore.nuspec, so I'd like to move that to the root and call it SgmlReader.nuspec.  Then I need to rework how strong naming works using a public key instead of a pfx since dotnet core doesn't support pfx based strong naming.  The UWP project remains because it provides an important implementation of IEntityResolver that connects with the UWP StorageFile API.  As for all the other changes regarding one class per file, nullable types, and async support I would like to make all of those separate pull requests.  For separate files I'm not a huge fan.  I typically don't like enums having their own file, just seems a bit excessive and reminds me too much of Java.  Some of the private types could move to nested classes, like HWStack and Node.

**Comment by daiplusplus** [comment]
@lovettchris No, I'm not abandoning #12 - I was just doing this as it was on my wish-list while I had the SgmlReader repo open on my computer.

**Comment by daiplusplus** [comment]
@lovettchris Regarding your comments in this reply: https://github.com/lovettchris/SgmlReader/pull/21#issuecomment-882840623  - can I ping you on Teams, Slack, Gitter, StackOverflow Chat for a few minutes? I have some questions

**EDIT:** I think I see you on Teams, but it would be improper without asking you first :)

**Comment by lovettchris** [comment]
Teams works, send me an email and I'll send you a teams link, let me know what time, in US pacific time, works for you.  My email is the first letter of my first name plus my last name at microsoft dot com.

**Pull request closed without merging**
